/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include "main.h"

char RxBuffer[256]="";
char TxBuffer[256]="";
bool CommandReceived = false;

int main(void)
{
  init_clk();
  init_servo();
  init_usart2();

    while(1)
    {
      if (CommandReceived)
      {
        execute_command();
      }
    }
}

// Прерывание USART
void USART2_IRQHandler(void) //обработка прерываний по USART2
{
  if ((USART2->SR & USART_SR_RXNE)!=0) // проверка, что прерывание пришло по приему данных
  {									   //флаг очищается чтением регистра USART_DR, поэтому его обновлять самим не нужно
    uint8_t len = strlen(RxBuffer);

    RxBuffer[len] = USART2->DR;// чтение регистра данных и сброс прерывания

    len = strlen(RxBuffer);
    if (len > 1)
    {
      if (RxBuffer[len-2]==0x0D && RxBuffer[len-1]==0x0A) //проверка на стоп биты
      {
        CommandReceived = true; //строка обработана
      }
    }

  }
}

void execute_command(void)
{
  memset(TxBuffer, 0, sizeof(TxBuffer));

  if (strncmp(RxBuffer, "*IDN?", 5) == 0)
  {
    strcpy(TxBuffer, "HW, Drantsev S.A., ICS4-73");
  }
  else if (strncmp(RxBuffer, "SERVO", 5) == 0)
  {
      int degree = -1;

      // Считываем одну цифру после "SET "
      sscanf(RxBuffer, "SERVO %d", &degree);
      if (degree >= 0 && degree <= 180) {
          rotate_servo(degree);
          sprintf(TxBuffer, "Success! %d was read", degree);
      } else {
          strcpy(TxBuffer, "ERROR: Invalid SERVO format; must be:\n\n\t> SERVO ddd\n\t(0 <= ddd <= 180)\n");
      }
  }
  else
  {
    strcpy(TxBuffer, "ERROR: Unknown Command");
  }

  usart2_transmit(TxBuffer);

  memset(RxBuffer, 0, sizeof(RxBuffer)); //записываем, в какой участок памяти записать опр. байты (нули) и какого размера
  CommandReceived = false;
}
