/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include "main.h"

char RxBuffer[256]="";
char TxBuffer[256]="";
bool CommandReceived = false;

uint8_t INIT_DEGREE = 0;

void init_clk(void)					/*Настройка внешнего генератора как источник тактирования на 64МГц*/
{
  // Enable HSI
  RCC->CR |= RCC_CR_HSION;
  while(!(RCC->CR & RCC_CR_HSIRDY)){};

  // Enable Prefetch Buffer
  FLASH->ACR |= FLASH_ACR_PRFTBE;

  // Flash 2 wait state
  FLASH->ACR &= ~FLASH_ACR_LATENCY;
  FLASH->ACR |= FLASH_ACR_LATENCY_2;

  // HCLK = SYSCLK
  RCC->CFGR |= RCC_CFGR_HPRE_DIV1;

  // PCLK2 = HCLK
  RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

  // PCLK1 = HCLK
  RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;

  // PLL configuration: PLLCLK = HSI/2 * 16 = 64 MHz
  RCC->CFGR &= ~RCC_CFGR_PLLSRC;
  RCC->CFGR |= RCC_CFGR_PLLMULL16;

  // Enable PLL
  RCC->CR |= RCC_CR_PLLON;

  // Wait till PLL is ready
  while((RCC->CR & RCC_CR_PLLRDY) == 0) {};

  // Select PLL as system clock source
  RCC->CFGR &= ~RCC_CFGR_SW;
  RCC->CFGR |= RCC_CFGR_SW_PLL;

  // Wait till PLL is used as system clock source
  while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL){};
}

// ---- Servo ----
uint8_t OFFSET = 50;

uint8_t transformDegree(uint8_t degree)
{
  if (degree > 180)
  {
    return degree = 180;
  }

  return degree + OFFSET;
}

void rotate_servo(uint8_t degree)
{
  TIM2->CCR1 = transformDegree(degree);
}

void init_servo(void)
{
  // Тактирование TIM2 и порта A
  RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;

  // General output push-pull 50MHz (PA1)
  GPIOA->CRL &= ~(GPIO_CRL_CNF0 | GPIO_CRL_MODE0);
  GPIOA->CRL |= GPIO_CRL_CNF0_1 | GPIO_CRL_MODE0;

  // Таймер в режим PWM
  // PWM mode 1 - In upcounting
  TIM2->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1;
  TIM2->PSC = 640 - 1;					/*Настройка Prescaler - предделитель*/
  TIM2->ARR = 2000; // 50Hz
  rotate_servo(INIT_DEGREE);
  // Capture/compare 1 output enabled
  TIM2->CCER |= TIM_CCER_CC1E;
  // Counter Enable
  TIM2->CR1 |= TIM_CR1_CEN;
}

// ---- USART ----
void init_usart2(void)
{
  //pa2 - tx
  //pa3 - rx
  RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;	 //тактирование порта
  RCC->APB1ENR |= RCC_APB1ENR_USART2EN ; // тактирование юсарта2
  RCC->APB2ENR |= RCC_APB2ENR_AFIOEN; // тактирование альтернативных функций
  //настройка pa2, pa3 - по умолчанию плавающий вход, не трогаем
  GPIOA->CRL |= GPIO_CRL_MODE2; //MODE = 11, Output 50MHz
  GPIOA->CRL &= ~GPIO_CRL_CNF2_0; //CNF = 00
  GPIOA->CRL |= GPIO_CRL_CNF2_1; //CNF = 10, Alternate Push-Pull
  
  //настроить скорость передачи данных:
  //Fck = 32 МГц, тк в 2 раза меньше чем на АПБ2 - 64/2=32
  //19200
  //32МГц/ (16 * 57600) = 34.7 - в хексе 34 это 22, 0,7*16=11,2 - к 22 пишем целую часть 11
  //итого: 0x0271
  USART2->BRR = 556; //регистр с целой и дробной частью
  //BRR - Baud Rate Register
  
  USART2->CR1 |= USART_CR1_UE | USART_CR1_RE | USART_CR1_TE | USART_CR1_RXNEIE; // CR - Configuration Register
  //UE - USART Enable, RE - Receiver Enable, TE - Transmitter Enable, RXNEIE - RX Not Empty Interrupt Enable
  NVIC_EnableIRQ(USART2_IRQn); // разрешили прерывание для USART2
  NVIC_SetPriority(USART2_IRQn, 0); // выставили приоритет
}

void usart2_transmit (char *str)
{
  strcat(str, "\r\n"); //добавляем стоп биты в передаваемую строку
  
  for (uint8_t i=0; i<strlen(str); i++)
  {
    USART2->DR = str[i]; //после этой строчки начнется передача данных
    while((USART2->SR & USART_SR_TC)==0); // TC - Transmission Complete
  }
}

void USART2_IRQHandler(void) //обработка прерываний по USART2
{
  if ((USART2->SR & USART_SR_RXNE)!=0) // проверка, что прерывание пришло по приему данных
  {									   //флаг очищается чтением регистра USART_DR, поэтому его обновлять самим не нужно
    uint8_t len = strlen(RxBuffer);

    RxBuffer[len] = USART2->DR;// чтение регистра данных и сброс прерывания

    len = strlen(RxBuffer);
    if (len > 1)
    {
      if (RxBuffer[len-2]==0x0D && RxBuffer[len-1]==0x0A) //проверка на стоп биты
      {
        CommandReceived = true; //строка обработана
      }
    }

  }
}

void ExecuteCommand(void)
{
  memset(TxBuffer, 0, sizeof(TxBuffer));

  if (strncmp(RxBuffer, "*IDN?", 5) == 0)
  {
    strcpy(TxBuffer, "HW, Drantsev S.A., ICS4-73");
  }
  else if (strncmp(RxBuffer, "SERVO", 5) == 0)
  {
      int degree = -1;

      // Считываем одну цифру после "SET "
      sscanf(RxBuffer, "SERVO %d", &degree);
      if (degree >= 0 && degree <= 180) {
          rotate_servo(degree);
          sprintf(TxBuffer, "Success! %d was read", degree);
      } else {
          strcpy(TxBuffer, "ERROR: Invalid SERVO format; must be:\n\n\t> SERVO ddd\n");
      }
  }
  else
  {
    strcpy(TxBuffer, "Unknown Command");
  }

  usart2_transmit(TxBuffer);

  memset(RxBuffer, 0, sizeof(RxBuffer)); //записываем, в какой участок памяти записать опр. байты (нули) и какого размера
  CommandReceived = false;
}

// ---- Utils ----
void delay(uint32_t takts)
{
	for (uint32_t i = 0; i < takts; i++) {};
}

int main(void)
{
  init_clk();
  init_servo();
  init_usart2();

    while(1)
    {
      if (CommandReceived)
      {
        ExecuteCommand();
      }
    }
}
